#include <unity.h>

void test_crc16_ibm_known_vector();

void test_dashboard_codec_accepts_and_normalizes_complete_draft();
void test_dashboard_codec_rejects_unknown_sensor_type();
void test_dashboard_codec_rejects_incompatible_json_types();
void test_dashboard_codec_rejects_duplicate_ids_and_short_scenes();
void test_dashboard_codec_refuses_lossy_legacy_scene();
void test_dashboard_codec_serializes_lossless_legacy_scene_with_warning();
void test_dashboard_codec_prepares_explicit_legacy_upgrade();
void test_dashboard_codec_rejects_empty_legacy_scene_upgrade();
void test_dashboard_codec_marks_last_good_recovery();
void test_dashboard_codec_replace_tiles_preserves_unrelated_config();
void test_dashboard_codec_accepts_schema_v3_editor_envelope();
void test_dashboard_codec_serializes_external_layout_source();
void test_dashboard_codec_replace_tiles_can_preserve_schema_v2();

void test_layout_codec_accepts_named_layout_with_spaces();
void test_layout_codec_rejects_invalid_identity_and_name();
void test_layout_filename_contract();

void test_runtime_state_codec_serializes_known_switch_state_and_age();
void test_runtime_state_codec_preserves_unknown_sensor_state();
void test_runtime_state_codec_aggregates_scene_switches_and_member_values();
void test_runtime_state_codec_age_survives_millis_wraparound();
void test_dashboard_fingerprint_ignores_runtime_values_but_tracks_configuration();

void test_admin_page_contains_hybrid_dashboard_editor();
void test_admin_page_uses_whole_dashboard_api_without_live_control();
void test_admin_page_contains_layout_source_management();
void test_admin_page_supports_read_only_live_scene_navigation();

void test_haptic_press_pulse_is_bounded();
void test_haptic_long_press_restarts_feedback_window();
void test_haptic_stop_turns_active_pulse_off_immediately();

void test_screen_power_timeout_turns_display_off();
void test_screen_power_wake_gesture_is_consumed_through_release();
void test_screen_power_does_not_sleep_under_active_touch();

void test_press_gesture_short_press_on_release_before_threshold();
void test_press_gesture_long_press_emits_once_and_consumes_release();
void test_press_gesture_cancel_suppresses_action_until_release();

void test_tile_behavior_resolves_gestures_independently_of_tile_type();

void test_status_center_cycle_uses_four_seconds_time_two_seconds_ip();
void test_status_center_cycle_handles_single_available_source();

void test_ui_change_preserves_model_item_coordinates();

void test_ui_controller_home_paging_and_navigation_bounds();
void test_ui_controller_back_returns_to_originating_home_page();
void test_ui_controller_home_action_returns_to_first_page();
void test_ui_controller_short_switch_press_emits_target_state_command();
void test_ui_controller_scene_toggle_uses_all_switch_state();
void test_ui_controller_long_press_opens_detail_and_requests_long_haptic();
void test_ui_controller_sensor_short_press_opens_detail_without_command();
void test_ui_controller_detail_item_toggle_emits_item_command();
void test_ui_controller_rejects_non_switch_and_out_of_range_items();
void test_ui_controller_detail_paging_respects_layout_metrics();
void test_ui_controller_footer_visibility_tracks_navigation_context();
void test_ui_controller_display_mode_change_does_not_wake_sleeping_screen();
void test_ui_controller_config_replacement_resets_navigation_and_wakes_screen();
void test_ui_controller_layout_change_clamps_invalid_pages();
void test_ui_controller_message_state_round_trips();

void setUp() {}
void tearDown() {}

int main(int, char**) {
  UNITY_BEGIN();

  RUN_TEST(test_crc16_ibm_known_vector);

  RUN_TEST(test_dashboard_codec_accepts_and_normalizes_complete_draft);
  RUN_TEST(test_dashboard_codec_rejects_unknown_sensor_type);
  RUN_TEST(test_dashboard_codec_rejects_incompatible_json_types);
  RUN_TEST(test_dashboard_codec_rejects_duplicate_ids_and_short_scenes);
  RUN_TEST(test_dashboard_codec_refuses_lossy_legacy_scene);
  RUN_TEST(test_dashboard_codec_serializes_lossless_legacy_scene_with_warning);
  RUN_TEST(test_dashboard_codec_prepares_explicit_legacy_upgrade);
  RUN_TEST(test_dashboard_codec_rejects_empty_legacy_scene_upgrade);
  RUN_TEST(test_dashboard_codec_marks_last_good_recovery);
  RUN_TEST(test_dashboard_codec_replace_tiles_preserves_unrelated_config);
  RUN_TEST(test_dashboard_codec_accepts_schema_v3_editor_envelope);
  RUN_TEST(test_dashboard_codec_serializes_external_layout_source);
  RUN_TEST(test_dashboard_codec_replace_tiles_can_preserve_schema_v2);

  RUN_TEST(test_layout_codec_accepts_named_layout_with_spaces);
  RUN_TEST(test_layout_codec_rejects_invalid_identity_and_name);
  RUN_TEST(test_layout_filename_contract);

  RUN_TEST(test_runtime_state_codec_serializes_known_switch_state_and_age);
  RUN_TEST(test_runtime_state_codec_preserves_unknown_sensor_state);
  RUN_TEST(test_runtime_state_codec_aggregates_scene_switches_and_member_values);
  RUN_TEST(test_runtime_state_codec_age_survives_millis_wraparound);
  RUN_TEST(test_dashboard_fingerprint_ignores_runtime_values_but_tracks_configuration);

  RUN_TEST(test_admin_page_contains_hybrid_dashboard_editor);
  RUN_TEST(test_admin_page_uses_whole_dashboard_api_without_live_control);
  RUN_TEST(test_admin_page_contains_layout_source_management);
  RUN_TEST(test_admin_page_supports_read_only_live_scene_navigation);

  RUN_TEST(test_haptic_press_pulse_is_bounded);
  RUN_TEST(test_haptic_long_press_restarts_feedback_window);
  RUN_TEST(test_haptic_stop_turns_active_pulse_off_immediately);

  RUN_TEST(test_screen_power_timeout_turns_display_off);
  RUN_TEST(test_screen_power_wake_gesture_is_consumed_through_release);
  RUN_TEST(test_screen_power_does_not_sleep_under_active_touch);

  RUN_TEST(test_press_gesture_short_press_on_release_before_threshold);
  RUN_TEST(test_press_gesture_long_press_emits_once_and_consumes_release);
  RUN_TEST(test_press_gesture_cancel_suppresses_action_until_release);

  RUN_TEST(test_tile_behavior_resolves_gestures_independently_of_tile_type);

  RUN_TEST(test_status_center_cycle_uses_four_seconds_time_two_seconds_ip);
  RUN_TEST(test_status_center_cycle_handles_single_available_source);

  RUN_TEST(test_ui_change_preserves_model_item_coordinates);

  RUN_TEST(test_ui_controller_home_paging_and_navigation_bounds);
  RUN_TEST(test_ui_controller_back_returns_to_originating_home_page);
  RUN_TEST(test_ui_controller_home_action_returns_to_first_page);
  RUN_TEST(test_ui_controller_short_switch_press_emits_target_state_command);
  RUN_TEST(test_ui_controller_scene_toggle_uses_all_switch_state);
  RUN_TEST(test_ui_controller_long_press_opens_detail_and_requests_long_haptic);
  RUN_TEST(test_ui_controller_sensor_short_press_opens_detail_without_command);
  RUN_TEST(test_ui_controller_detail_item_toggle_emits_item_command);
  RUN_TEST(test_ui_controller_rejects_non_switch_and_out_of_range_items);
  RUN_TEST(test_ui_controller_detail_paging_respects_layout_metrics);
  RUN_TEST(test_ui_controller_footer_visibility_tracks_navigation_context);
  RUN_TEST(test_ui_controller_display_mode_change_does_not_wake_sleeping_screen);
  RUN_TEST(test_ui_controller_config_replacement_resets_navigation_and_wakes_screen);
  RUN_TEST(test_ui_controller_layout_change_clamps_invalid_pages);
  RUN_TEST(test_ui_controller_message_state_round_trips);

  return UNITY_END();
}
